[language-server.gopls.config]
"formatting.gofumpt" = false

[[language]]
name = "python"
roots = [
  "pyproject.toml",
  "main.py",
  "setup.py",
  "requirements.txt",
  "pyrightconfig.json",
]
language-servers = [ "pyright" ]
auto-format = true 

[language.formatter]
command = "black"
args = ["--line-length", "88", "--quiet", "-"]

[[language]]
name = "html"
language-servers= [ "vscode-html-language-server", "tailwindcss-ls" ]

[[language]]
name = "css"
language-servers= [ "vscode-css-language-server", "tailwindcss-ls" ]

[[language]]
name = "jsx"
language-servers= [ "typescript-language-server", "tailwindcss-ls" ]

[[language]]
name = "tsx"
language-servers= [ "typescript-language-server", "tailwindcss-ls" ]

[[language]]
name = "svelte"
language-servers= [ "svelteserver", "tailwindcss-ls" ]


[language-server]

terraform-ls = { command = "terraform-ls", args = ["serve"] }

[[language]]
name = "hcl"
scope = "source.hcl"
injection-regex = "(hcl|tf|nomad)"
language-id = "terraform"
file-types = ["hcl", "tf", "nomad"]
comment-token = "#"
block-comment-tokens = { start = "/*", end = "*/" }
indent = { tab-width = 2, unit = "  " }
language-servers = [ "terraform-ls" ]
auto-format = true

[[language]]
name = "tfvars"
scope = "source.tfvars"
language-id = "terraform-vars"
file-types = ["tfvars"]
comment-token = "#"
block-comment-tokens = { start = "/*", end = "*/" }
indent = { tab-width = 2, unit = "  " }
language-servers = [ "terraform-ls" ]
auto-format = true
grammar = "hcl"
